# Generated by Django 5.1.1 on 2024-09-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AuthApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
