# Generated by Django 5.1.1 on 2024-09-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TeacherApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="code",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
