# Generated by Django 5.1.1 on 2024-09-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TeacherApp", "0002_courses_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="quiz_added",
            field=models.BooleanField(default=False),
        ),
    ]
