# Generated by Django 5.1.1 on 2024-09-24 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TeacherApp", "0003_courses_quiz_added"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(null=True)),
                ("correct_answer", models.CharField(max_length=255, null=True)),
                ("incorrect_answers", models.JSONField(null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TeacherApp.courses",
                    ),
                ),
            ],
        ),
    ]
