# Generated by Django 5.1.1 on 2024-09-25 06:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("StudentApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quizsubmissiondetails",
            old_name="course_id",
            new_name="course",
        ),
    ]
